// const coins=[
//     {
//         "id": 1,
//         "symbol" : "BTC/KRW",
//         "name" : "비트코인",
//         "marketCap" : "970조 9007억",
//     },
//     {
//         "id": 2,
//         "symbol" : "ETH/KRW",
//         "name" : "이더리움",
//         "marketCap" : "458조 0513억",
//     },
//     {
//         "id": 3,
//         "symbol" : "BNB/KRW",
//         "name" : "바이낸스 코인",
//         "marketCap" : "84조 6130억",
//     },
//     {
//         "id": 4,
//         "symbol" : "XRP/KRW",
//         "name" : "리플",
//         "marketCap" : "44조 7788억",
//     },
//     {
//         "id": 5,
//         "symbol" : "SQL/KRW",
//         "name" : "솔라나",
//         "marketCap" : "43조 8142억",
//     },
//     {
//         "id": 6,
//         "symbol" : "LUNA/KRW",
//         "name" : "루나",
//         "marketCap" : "970조 9007억",
//     },
//     {
//         "id": 7,
//         "symbol" : "ADA/KRW",
//         "name" : "에이다",
//     },
//     {
//         "id": 8,
//         "symbol" : "AVAX/KRW",
//         "name" : "아발란체",
//     },
//     {
//         "id": 9,
//         "symbol" : "DOGE/KRW",
//         "name" : "도지코인",
//     },
//     {
//         "id": 10,
//         "symbol" : "DOT/KRW",
//         "name" : "폴카닷",
//     },
//     {
//         "id": 11,
//         "symbol" : "MATIC/KRW",
//         "name" : "폴리곤",
//     },
//     {
//         "id": 12,
//         "symbol" : "CRO/KRW",
//         "name" : "크로노스",
//     },
//     {
//         "id": 13,
//         "symbol" : "DAI/KRW",
//         "name" : "다이",
//     },
//     {
//         "id": 14,
//         "symbol" : "LTC/KRW",
//         "name" : "라이트코인",
//     },
//     {
//         "id": 15,
//         "symbol" : "ATOM/KRW",
//         "name" : "코스모스",
//     },
//     {
//         "id": 16,
//         "symbol" : "LINK/KRW",
//         "name" : "체인링크",
//     },
//     {
//         "id": 17,
//         "symbol" : "UNI/KRW",
//         "name" : "유니스왑",
//     },
//     {
//         "id": 18,
//         "symbol" : "BCH/KRW",
//         "name" : "비트코인 캐시",
//     },
//     {
//         "id": 19,
//         "symbol" : "TRX/KRW",
//         "name" : "트론",
//     },
//     {
//         "id": 20,
//         "symbol" : "ALGO/KRW",
//         "name" : "알고랜드",
//     },
//     {
//         "id": 21,
//         "symbol" : "XLM/KRW",
//         "name" : "스텔라루멘",
//     },
//     {
//         "id": 22,
//         "symbol" : "ETC/KRW",
//         "name" : "이더리움 클래식",
//     },
//     {
//         "id": 23,
//         "symbol" : "MANA/KRW",
//         "name" : "디센트럴랜드",
//     },
//     {
//         "id": 24,
//         "symbol" : "VET/KRW",
//         "name" : "비체인",
//     },
//     {
//         "id": 25,
//         "symbol" : "EGLD/KRW",
//         "name" : "엘론드",
//     },
//     {
//         "id": 26,
//         "symbol" : "SAND/KRW",
//         "name" : "샌드박스",
//     },
//     {
//         "id": 27,
//         "symbol" : "THETA/KRW",
//         "name" : "쎄타토큰",
//     },
//     {
//         "id": 28,
//         "symbol" : "AXS/KRW",
//         "name" : "엑시인피니티",
//     },
//     {
//         "id": 29,
//         "symbol" : "XTZ/KRW",
//         "name" : "테조스",
//     },
//     {
//         "id": 30,
//         "symbol" : "KLAY/KRW",
//         "name" : "클레이톤",
//     },
//     {
//         "id": 31,
//         "symbol" : "AAVE/KRW",
//         "name" : "에이브",
//     },
//     {
//         "id": 32,
//         "symbol" : "EOS/KRW",
//         "name" : "이오스",
//     },
//     {
//         "id": 33,
//         "symbol" : "CAKE/KRW",
//         "name" : "팬케이크스왑",
//     },
//     {
//         "id": 34,
//         "symbol" : "WAVES/KRW",
//         "name" : "웨이브",
//     },
//     {
//         "id": 35,
//         "symbol" : "MKR/KRW",
//         "name" : "메이커",
//     },
//     {
//         "id": 36,
//         "symbol" : "GRT/KRW",
//         "name" : "더그래프",
//     },
//     {
//         "id": 37,
//         "symbol" : "BTT/KRW",
//         "name" : "비트토렌트",
//     },
//     {
//         "id": 38,
//         "symbol" : "XEC/KRW",
//         "name" : "이캐시",
//     },
//     {
//         "id": 39,
//         "symbol" : "BSV/KRW",
//         "name" : "비트코인에스브이",
//     },
//     {
//         "id": 40,
//         "symbol" : "KSM/KRW",
//         "name" : "쿠사마",
//     },
//     {
//         "id": 41,
//         "symbol" : "ZIL/KRW",
//         "name" : "질리카",
//     },
//     {
//         "id": 42,
//         "symbol" : "GALA/KRW",
//         "name" : "갈라",
//     },
//     {
//         "id": 43,
//         "symbol" : "CHZ/KRW",
//         "name" : "칠리즈",
//     },
//     {
//         "id": 44,
//         "symbol" : "ENJ/KRW",
//         "name" : "엔진코인",
//     },
//     {
//         "id": 45,
//         "symbol" : "LRC/KRW",
//         "name" : "루프링",
//     },
//     {
//         "id": 46,
//         "symbol" : "BAT/KRW",
//         "name" : "베이직어텐션토큰",
//     },
//     {
//         "id": 47,
//         "symbol" : "COMP/KRW",
//         "name" : "컴파운드",
//     },
//     {
//         "id": 48,
//         "symbol" : "XEM/KRW",
//         "name" : "넴",
//     },
//     {
//         "id": 49,
//         "symbol" : "TFUEL/KRW",
//         "name" : "쎼타퓨엘",
//     },
//     {
//         "id": 50,
//         "symbol" : "SNX/KRW",
//         "name" : "신세틱스",
//     },
//     {
//         "id": 51,
//         "symbol" : "ICX/KRW",
//         "name" : "아이콘",
//     },
//     {
//         "id": 52,
//         "symbol" : "QTUM/KRW",
//         "name" : "퀸텀",
//     },
//     {
//         "id":53,
//         "symbol" : "BORA/KRW",
//         "name" : "보라",
//     },
//     {
//         "id": 54,
//         "symbol" : "YFI/KRW",
//         "name" : "연파이낸스",
//     },
//     {
//         "id": 55,
//         "symbol" : "OMG/KRW",
//         "name" : "오미세고",
//     },
//     {
//         "id": 56,
//         "symbol" : "XYM/KRW",
//         "name" : "심볼",
//     },
//     {
//         "id": 57,
//         "symbol" : "SXP/KRW",
//         "name" : "스와이프",
//     },
//     {
//         "id": 58,
//         "symbol" : "SRM/KRW",
//         "name" : "세럼",
//     },
//     {
//         "id": 59,
//         "symbol" : "1INCH/KRW",
//         "name" : "1인치",
//     },
//     {
//         "id": 60,
//         "symbol" : "ANKR/KRW",
//         "name" : "앵커",
//     },
//     {
//         "id": 61,
//         "symbol" : "ZRX/KRW",
//         "name" : "제로엑스",
//     },
//     {
//         "id": 62,
//         "symbol" : "BTG/KRW",
//         "name" : "비트코인 골드",
//     },
//     {
//         "id": 63,
//         "symbol" : "BNT/KRW",
//         "name" : "뱅코르",
//     },
//     {
//         "id": 64,
//         "symbol" : "IOST/KRW",
//         "name" : "이오스트",
//     },
//     {
//         "id": 65,
//         "symbol" : "WAXP/KRW",
//         "name" : "왁스",
//     },
//     {
//         "id": 66,
//         "symbol" : "JST/KRW",
//         "name" : "저스트",
//     },
//     {
//         "id": 67,
//         "symbol" : "WOO/KRW",
//         "name" : "우네트워크",
//     },
//     {
//         "id": 68,
//         "symbol" : "LPT/KRW",
//         "name" : "라이브피어",
//     },
//     {
//         "id": 69,
//         "symbol" : "ONT/KRW",
//         "name" : "온톨로지",
//     },
//     {
//         "id": 70,
//         "symbol" : "WEMIX/KRW",
//         "name" : "위믹스",
//     },
//     {
//         "id": 71,
//         "symbol" : "NFT/KRW",
//         "name" : "에이피이앤에프티",
//     },
//     {
//         "id": 72,
//         "symbol" : "RLY/KRW",
//         "name" : "랠리",
//     },
//     {
//         "id": 73,
//         "symbol" : "SUSHI/KRW",
//         "name" : "스시스왑",
//     },
//     {
//         "id": 74,
//         "symbol" : "GLM/KRW",
//         "name" : "골렘",
//     },
//     {
//         "id": 75,
//         "symbol" : "UMA/KRW",
//         "name" : "우마",
//     },
//     {
//         "id": 76,
//         "symbol" : "REN/KRW",
//         "name" : "렌",
//     },
//     {
//         "id": 77,
//         "symbol" : "HIVE/KRW",
//         "name" : "하이브",
//     },
//     {
//         "id": 78,
//         "symbol" : "CELR/KRW",
//         "name" : "셀러네트워크",
//     },
//     {
//         "id": 79,
//         "symbol" : "CKB/KRW",
//         "name" : "너보스",
//     },
//     {
//         "id": 80,
//         "symbol" : "CSPR/KRW",
//         "name" : "캐스퍼",
//     },
//     {
//         "id": 81,
//         "symbol" : "OCEAN/KRW",
//         "name" : "오션프로토콜",
//     },
//     {
//         "id": 82,
//         "symbol" : "UOS/KRW",
//         "name" : "울트라",
//     },
//     {
//         "id": 83,
//         "symbol" : "C98/KRW",
//         "name" : "코인98",
//     },
//     {
//         "id": 84,
//         "symbol" : "KNC/KRW",
//         "name" : "카이버 네트워크",
//     },
//     {
//         "id": 85,
//         "symbol" : "COTI/KRW",
//         "name" : "코티",
//     },
//     {
//         "id": 86,
//         "symbol" : "MXC/KRW",
//         "name" : "머신익스체인지코인",
//     },
//     {
//         "id": 87,
//         "symbol" : "CHR/KRW",
//         "name" : "크로미아",
//     },
//     {
//         "id": 88,
//         "symbol" : "POWR/KRW",
//         "name" : "파워렛저",
//     },
//     {
//         "id": 89,
//         "symbol" : "MED/KRW",
//         "name" : "메디블록",
//     },
//     {
//         "id": 90,
//         "symbol" : "ONG/KRW",
//         "name" : "온톨로지가스",
//     },
//     {
//         "id": 91,
//         "symbol" : "PUNDIX/KRW",
//         "name" : "펀디엑스",
//     },
//     {
//         "id": 92,
//         "symbol" : "SNT/KRW",
//         "name" : "스테이터스네트워크토큰",
//     },
//     {
//         "id":93 ,
//         "symbol" : "ORBS/KRW",
//         "name" : "오브스",
//     },
//     {
//         "id":94 ,
//         "symbol" : "RSR/KRW",
//         "name" : "리저브라이트",
//     },
//     {
//         "id":95 ,
//         "symbol" : "BOBA/KRW",
//         "name" : "보바토큰",
//     },
//     {
//         "id": 96,
//         "symbol" : "ALICE/KRW",
//         "name" : "마이네이버앨리스",
//     },
//     {
//         "id": 97,
//         "symbol" : "FX/KRW",
//         "name" : "펑션엑스",
//     },    
//     {
//         "id": 98,
//         "symbol" : "MTL/KRW",
//         "name" : "메탈",
//     },
//     {
//         "id": 99,
//         "symbol" : "CTSI/KRW",
//         "name" : "카르테시",
//     },
//     {
//         "id": 100,
//         "symbol" : "DAO/KRW",
//         "name" : "다오메이커",
//     },
//     {
//         "id": 101,
//         "symbol" : "ORC/KRW",
//         "name" : "오르빗 체인",
//     },
//     {
//         "id": 102,
//         "symbol" : "ELF/KRW",
//         "name" : "엘프",
//     },
//     {
//         "id": 103,
//         "symbol" : "OXT/KRW",
//         "name" : "오키드",
//     },
//     {
//         "id": 104,
//         "symbol" : "RLC/KRW",
//         "name" : "아이젝",
//     },
//     {
//         "id": 105,
//         "symbol" : "BFC/KRW",
//         "name" : "바이프로스트",
//     },
//     {
//         "id": 106,
//         "symbol" : "TITAN/KRW",
//         "name" : "타이탄스왑",
//     },
//     {
//         "id": 107,
//         "symbol" : "NMR/KRW",
//         "name" : "뉴메레르",
//     },
//     {
//         "id": 108,
//         "symbol" : "SUN/KRW",
//         "name" : "썬",
//     },
//     {
//         "id": 109,
//         "symbol" : "ACH/KRW",
//         "name" : "알케미페이",
//     },
//     {
//         "id": 110,
//         "symbol" : "REP/KRW",
//         "name" : "어거",
//     },
//     {
//         "id": 111,
//         "symbol" : "STRAX/KRW",
//         "name" : "스트라티스",
//     },
//     {
//         "id": 112,
//         "symbol" : "MBL/KRW",
//         "name" : "무비블록",
//     },
//     {
//         "id":113 ,
//         "symbol" : "STEEM/KRW",
//         "name" : "스팀",
//     },
//     {
//         "id":114 ,
//         "symbol" : "QKC/KRW",
//         "name" : "쿼크체인",
//     },
//     {
//         "id":115 ,
//         "symbol" : "META/KRW",
//         "name" : "메타디움",
//     },
//     {
//         "id": 116,
//         "symbol" : "XVS/KRW",
//         "name" : "비너스",
//     },
//     {
//         "id": 117,
//         "symbol" : "SSX/KRW",
//         "name" : "썸씽",
//     },
//     {
//         "id": 118,
//         "symbol" : "DVI/KRW",
//         "name" : "디비전",
//     },
//     {
//         "id": 119,
//         "symbol" : "CENNZ/KRW",
//         "name" : "센트럴리티",
//     },
//     {
//         "id": 120,
//         "symbol" : "XPR/KRW",
//         "name" : "프로톤",
//     },
//     {
//         "id": 121,
//         "symbol" : "MIR/KRW",
//         "name" : "미러 프로토콜",
//     },
//     {
//         "id": 122,
//         "symbol" : "BAL/KRW",
//         "name" : "밸런서",
//     },
//     {
//         "id": 123,
//         "symbol" : "LINA/KRW",
//         "name" : "리니어파이낸스",
//     },
//     {
//         "id": 124,
//         "symbol" : "VRA/KRW",
//         "name" : "베라시티",
//     },
//     {
//         "id": 125,
//         "symbol" : "CTK/KRW",
//         "name" : "써틱",
//     },
//     {
//         "id": 126,
//         "symbol" : "AERGO/KRW",
//         "name" : "아르고",
//     },
//     {
//         "id": 127,
//         "symbol" : "EGG/KRW",
//         "name" : "네스트리",
//     },
//     {
//         "id": 128,
//         "symbol" : "ARPA/KRW",
//         "name" : "알파체인",
//     },
//     {
//         "id": 129,
//         "symbol" : "LOOM/KRW",
//         "name" : "룸네트워크",
//     },
//     {
//         "id": 130,
//         "symbol" : "BCD/KRW",
//         "name" : "비트코인 다이아몬드",
//     },
//     {
//         "id": 131,
//         "symbol" : "EFI/KRW",
//         "name" : "이피니티토큰",
//     },
//     {
//         "id": 132,
//         "symbol" : "AQT/KRW",
//         "name" : "알파쿼크",
//     },
//     {
//         "id": 133,
//         "symbol" : "CON/KRW",
//         "name" : "코넌",
//     },
//     {
//         "id": 134,
//         "symbol" : "WOZX/KRW",
//         "name" : "이포스",
//     },
//     {
//         "id": 135,
//         "symbol" : "VELO/KRW",
//         "name" : "벨로프로토콜",
//     },
//     {
//         "id": 136,
//         "symbol" : "MLK/KRW",
//         "name" : "밀크",
//     },
//     {
//         "id": 137,
//         "symbol" : "COS/KRW",
//         "name" : "콘텐토스",
//     },
//     {
//         "id": 138,
//         "symbol" : "BIOT/KRW",
//         "name" : "바이오패스포트",
//     },
//     {
//         "id": 139,
//         "symbol" : "DAD/KRW",
//         "name" : "다드",
//     },
//     {
//         "id": 140,
//         "symbol" : "ATOLO/KRW",
//         "name" : "라이즌",
//     },
//     {
//         "id": 141,
//         "symbol" : "ASM/KRW",
//         "name" : "어셈블프로토콜",
//     },
//     {
//         "id": 142,
//         "symbol" : "CTXC/KRW",
//         "name" : "코르텍스",
//     },
//     {
//         "id": 143,
//         "symbol" : "FRONT/KRW",
//         "name" : "프론티어",
//     },
//     {
//         "id": 144,
//         "symbol" : "MIX/KRW",
//         "name" : "믹스마블",
//     },
//     {
//         "id": 145,
//         "symbol" : "DFA/KRW",
//         "name" : "디파인",
//     },
//     {
//         "id": 146,
//         "symbol" : "AMO/KRW",
//         "name" : "아모코인",
//     },
//     {
//         "id": 147,
//         "symbol" : "AION/KRW",
//         "name" : "아이온",
//     },
//     {
//         "id": 148,
//         "symbol" : "BEL/KRW",
//         "name" : "벨라프로토콜",
//     },
//     {
//         "id": 149,
//         "symbol" : "MAP/KRW",
//         "name" : "맵프로토콜",
//     },
//     {
//         "id": 150,
//         "symbol" : "GOM2/KRW",
//         "name" : "고머니2",
//     },
//     {
//         "id": 151,
//         "symbol" : "FCT2/KRW",
//         "name" : "피르마체인",
//     },
//     {
//         "id": 152,
//         "symbol" : "MEV/KRW",
//         "name" : "미버스",
//     },
//     {
//         "id": 153,
//         "symbol" : "WTC/KRW",
//         "name" : "윌튼체인",
//     },
//     {
//         "id": 154,
//         "symbol" : "BOA/KRW",
//         "name" : "보아",
//     },
//     {
//         "id": 155,
//         "symbol" : "BASIC/KRW",
//         "name" : "베이직",
//     },
//     {
//         "id": 156,
//         "symbol" : "MVC/KRW",
//         "name" : "마일벌스",
//     },
//     {
//         "id": 157,
//         "symbol" : "BURGER/KRW",
//         "name" : "버거스왑",
//     },
//     {
//         "id": 158,
//         "symbol" : "VSYS/KRW",
//         "name" : "브이시스템즈",
//     },
//     {
//         "id": 159,
//         "symbol" : "SOFI/KRW",
//         "name" : "라이파이낸스",
//     },
//     {
//         "id": 160,
//         "symbol" : "WICC/KRW",
//         "name" : "웨이키체인",
//     },
//     {
//         "id": 161,
//         "symbol" : "GO/KRW",
//         "name" : "고체인",
//     },
//     {
//         "id": 162,
//         "symbol" : "QTCON/KRW",
//         "name" : "퀴즈톡",
//     },
//     {
//         "id": 163,
//         "symbol" : "TMTG/KRW",
//         "name" : "더마이다스터치골드",
//     },
//     {
//         "id": 164,
//         "symbol" : "EVZ/KRW",
//         "name" : "이브이지",
//     },
//     {
//         "id": 165,
//         "symbol" : "ADP/KRW",
//         "name" : "어댑터 토큰",
//     },
//     {
//         "id": 166,
//         "symbol" : "GHX/KRW",
//         "name" : "게이머코인",
//     },
//     {
//         "id": 167,
//         "symbol" : "XNO/KRW",
//         "name" : "제노토큰",
//     },
//     {
//         "id": 168,
//         "symbol" : "EL/KRW",
//         "name" : "엘리시아",
//     },
//     {
//         "id": 169,
//         "symbol" : "HIBS/KRW",
//         "name" : "힙스",
//     },
//     {
//         "id": 170,
//         "symbol" : "SOC/KRW",
//         "name" : "소다코인",
//     },
//     {
//         "id": 171,
//         "symbol" : "TEMCO/KRW",
//         "name" : "템코",
//     },
//     {
//         "id": 172,
//         "symbol" : "CYCLUB/KRW",
//         "name" : "싸이클럽",
//     },
//     {
//         "id": 173,
//         "symbol" : "OBSR/KRW",
//         "name" : "옵저버",
//     },
//     {
//         "id": 174,
//         "symbol" : "WIKEN/KRW",
//         "name" : "위드",
//     },
//     {
//         "id": 175,
//         "symbol" : "APM/KRW",
//         "name" : "에이피엠 코인",
//     },
//     {
//         "id": 176,
//         "symbol" : "IPX/KRW",
//         "name" : "타키온프로토콜",
//     },
//     {
//         "id": 177,
//         "symbol" : "WOM/KRW",
//         "name" : "왐토큰",
//     },
//     {
//         "id": 178,
//         "symbol" : "VALOR/KRW",
//         "name" : "밸러토큰",
//     },
//     {
//         "id": 179,
//         "symbol" : "TRV/KRW",
//         "name" : "트러스트버스",
//     },
//     {
//         "id": 180,
//         "symbol" : "BLY/KRW",
//         "name" : "블로서리",
//     },
//     {
//         "id": 181,
//         "symbol" : "RINGX/KRW",
//         "name" : "링엑스",
//     },
//     {
//         "id": 182,
//         "symbol" : "ANW/KRW",
//         "name" : "앵커뉴럴월드",
//     },
//     {
//         "id": 183,
//         "symbol" : "APIX/KRW",
//         "name" : "아픽스",
//     },
//     {
//         "id": 184,
//         "symbol" : "POLA/KRW",
//         "name" : "폴라리스 쉐어",
//     },
//     {
//         "id": 185,
//         "symbol" : "PCI/KRW",
//         "name" : "페이코인",
//     },
//     {
//         "id": 186,
//         "symbol" : "TDROP/KRW",
//         "name" : "티드랍",
//     },
//     {
//         "id": 187,
//         "symbol" : "CTC/KRW",
//         "name" : "크레딧코인",
//     },
//     {
//         "id": 188,
//         "symbol" : "CWD/KRW",
//         "name" : "크라우드",
//     },
//     {
//         "id": 189,
//         "symbol" : "COLA/KRW",
//         "name" : "콜라토큰",
//     },
//     {
//         "id": 190,
//         "symbol" : "AWO/KRW",
//         "name" : "에이아이워크",
//     },
//     {
//         "id": 191,
//         "symbol" : "ANV/KRW",
//         "name" : "애니버스",
//     },
//     {
//         "id": 192,
//         "symbol" : "ARW/KRW",
//         "name" : "아로와나토큰",
//     },
//     {
//         "id": 193,
//         "symbol" : "T/KRW",
//         "name" : "쓰레스홀드",
//     },
//     {
//         "id": 194,
//         "symbol" : "SPRT/KRW",
//         "name" : "스포티움",
//     },
//     {
//         "id": 195,
//         "symbol" : "MM/KRW",
//         "name" : "밀리미터토큰",
//     },
//     {
//         "id": 196,
//         "symbol" : "REI/KRW",
//         "name" : "레이",
//     },
//     {
//         "id": 197,
//         "symbol" : "NPT/KRW",
//         "name" : "네오핀",
//     },
//     {
//         "id": 198,
//         "symbol" : "FIT/KRW",
//         "name" : "300피트 네트워크",
//     },
// ]

// export default coins;

export const coinName = {
    '1INCH': '1인치',
    AAVE: '에이브',
    ACH: '알케미페이',
    ADA: '에이다',
    ADP: '어댑터 토큰',
    AERGO: '아르고',
    AION: '아이온',
    ALGO: '알고랜드',
    ALICE: '마이네이버앨리스',
    AMO: '아모코인',
    ANKR: '앵커',
    ANV: '애니버스',
    ANW: '앵커뉴럴월드',
    APIX: '아픽스',
    APM: '에이피엠 코인',
    AQT: '알파쿼크',
    ARPA: '알파체인',
    ARW: '아로와나',
    ASM: '어셈블프로토콜',
    ATOLO: '라이즌',
    ATOM: '코스모스',
    AVAX: '아발란체',
    AWO: '에이아이워크',
    AXS: '엑시인피니티',
    BAL: '밸런서',
    BASIC: '베이직',
    BAT: '베이직어텐션토큰',
    BCD: '비트코인 다이아몬드',
    BCH: '비트코인캐시',
    BEL: '벨라프로토콜',
    BFC: '바이프로스트',
    BIOT: '바이오패스포트',
    BLY: '블로서리',
    BNB: '바이낸스',
    BNT: '뱅코르',
    BOA: '보아',
    BOBA: '보바토큰',
    BORA: '보라',
    BSV: '비트코인에스브이',
    BTC: '비트코인',
    BTG: '비트코인골드',
    BTT: '비트토렌트',
    BURGER: '버거스왑',
    C98: '코인98',
    CAKE: '팬케이크스왑',
    CELR: '셀로네트워크',
    CENNZ: '센트럴리티',
    CHR: '크로미아',
    CHZ: '칠리즈',
    CKB: '너보스',
    COLA: '콜라토큰',
    COMP: '컴파운드',
    CON: '코넌',
    COS: '콘텐토스',
    COTI: '코티',
    CRO: '크로노스',
    CSPR: '캐스퍼',
    CTC: '크레딧코인',
    CTK: '써틱',
    CTSI: '카르테시',
    CTXC: '코르텍스',
    CWD: '크라우드',
    CYCLUB: '싸이클럽',
    DAD: '다드',
    DAI: '다이',
    DAO: '다오메이커',
    DFA: '디파인',
    DOGE: '도지코인',
    DOT: '폴카닷',
    DVI: '디비전',
    EFI: '이피니티토큰',
    EGG: '네스트리',
    EGLD: '엘론드',
    EL: '엘리시아',
    ELF: '엘프',
    ENJ: '엔진코인',
    EOS: '이오스',
    ETC: '이더리움클래식',
    ETH: '이더리움',
    EVZ: '이브이지',
    FCT2: '피르마체인',
    FIT: '300피트 네트워크',
    FRONT: '프론티어',
    FX: '펑션엑스',
    GALA: '갈라',
    GHX: '게이머코인',
    GLM: '골렘',
    GO: '고체인',
    GOM2: '고머니2',
    GRT: '더그래프',
    HIBS: '힙스',
    HIVE: '하이브',
    ICX: '아이콘',
    IOST: '이오스트',
    IPX: '타키온 프로토콜',
    JST: '저스트',
    KLAY: '클레이튼',
    KNC: '카이버 네트워크',
    KSM: '쿠사마',
    LINA: '리니어 파이낸스',
    LINK: '체인링크',
    LOOM: '룸네트워크',
    LPT: '라이브피어',
    LRC: '루프링',
    LTC: '라이트코인',
    LUNA: '루나',
    MANA: '디센트럴랜드',
    MAP: '맵프로토콜',
    MATIC: '폴리곤',
    MBL: '무비블록',
    MED: '메디블록',
    META: '메타디움',
    MEV: '미버스',
    MIR: '미러 프로토콜',
    MIX: '믹스마블',
    MKR: '메이커',
    MLK: '밀크',
    MM: '밀리미터토큰',
    MTL: '메탈',
    MVC: '마일벌스',
    MXC: '머신익스체인지코인',
    NFT: '에이피이앤에프티',
    NMR: '뉴메레르',
    NPT: '네오핀',
    OBSR: '옵저버',
    OCEAN: '오션프로토콜',
    OMG: '오미세고',
    ONG: '온톨로지가스',
    ONT: '온톨로지',
    ORBS: '오브스',
    ORC: '오르빗 체인',
    OXT: '오키드',
    PCI: '페이코인',
    PLA: '플레이댑',
    POLA: '폴라리스쉐어',
    POWR: '파워렛저',
    PUNDIX: '펀디엑스',
    QKC: '쿼크체인',
    QTCON: '퀴즈톡',
    QTUM: '퀀텀',
    REI: '레이',
    REN: '렌',
    REP: '어거',
    RINGX: '링엑스',
    RLC: '아이젝',
    RLY: '랠리',
    RSR: '리저브라이트',
    SAND: '샌드박스',
    SNT: '스테이터스네트워크토큰',
    SNX: '신세틱스',
    SOC: '소다코인',
    SOFI: '라이파이낸스',
    SOL: '솔라나',
    SPRT: '스포티움',
    SRM: '세럼',
    SSX: '썸씽',
    STEEM: '스팀',
    STRAX: '스트라티스',
    SUN: '썬',
    SUSHI: '스시스왑',
    SWAP: '트러스트스왑',
    SXP: '스와이프',
    T: '타임',
    TDROP: '티드랍',
    TEMCO: '템코',
    TFUEL: '쎄타퓨엘',
    THETA: '쎼타토큰',
    TITAN: '타이탄스왑',
    TMTG: '더마이다스터치골드',
    TRV: '트러스트버스',
    TRX: '트론',
    UMA: '우마',
    UNI: '유니스왑',
    UOS: '울트라',
    VALOR: '밸러토큰',
    VELO: '벨로프로토콜',
    VET: '비체인',
    VRA: '베라시티',
    VSYS: '브이시스템즈',
    WAVES: '웨이브',
    WAXP: '왁스',
    WEMIX: '위믹스',
    WICC: '웨이키체인',
    WIKEN: '위드',
    WOM: '왐토큰',
    WOO: '우네트워크',
    WOZX: '이포스',
    WTC: '월튼체인',
    XEC: '이캐시',
    XEM: '넴',
    XLM: '스텔라루멘',
    XNO: '제노토큰',
    XPR: '프로톤',
    XRP: '리플',
    XTZ: '테조스',
    XVS: '비너스',
    XYM: '심볼',
    YFI: '연파이낸스',
    ZIL: '질리카',
    ZRX: '제로엑스',
  };